[package]
name = "staticunit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.actix-web]
version = "4.5"
features = ["macros"]
default-features = false
[dependencies.actix-files]
version = "0.6"
